artifacts_root:artifacts

data_ingestion:
  root_dir:artifacts/data_ingestion
  source_url:https://github.com/Raju4327/Chicken-Fecal-Images/raw/main/Chicken-fecal-images.zip
  local_data_file:artifacts/data_ingestion/data.zip
  unzip_dir:artifacts/data_ingestion


prepare_base_model:
  root_dir:artifacts/prepare_base_model
  base_model_path:artifacts/prepare_base_model/base_model.h5
  upadate_base_model_path:artifacts/prepare_base_model/base_model_updated.h5



prepare_callbacks:
  root_dir:artifacts/prepare_callbacks
  base_model_path:artifacts/prepare_callbacks/tensorboard_log_dir
  upadate_base_model_path:artifacts/prepare_callbacks/checkpoing_dir/model.h5

